version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  data-mysql: